"""Comprehensive journal data with hundreds of journals by discipline."""

JOURNALS_BY_DISCIPLINE = {
    "Computer Science": [
        {"title": "IEEE Transactions on Pattern Analysis and Machine Intelligence", "issn": "0162-8828", "jcr_if": 24.314, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": True},
        {"title": "IEEE Transactions on Neural Networks and Learning Systems", "issn": "2162-237X", "jcr_if": 10.451, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE Transactions on Image Processing", "issn": "1057-7149", "jcr_if": 10.6, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE Transactions on Cybernetics", "issn": "2168-2267", "jcr_if": 11.8, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE Transactions on Evolutionary Computation", "issn": "1089-778X", "jcr_if": 14.3, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE Transactions on Fuzzy Systems", "issn": "1063-6706", "jcr_if": 11.6, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE Transactions on Knowledge and Data Engineering", "issn": "1041-4347", "jcr_if": 8.9, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE Transactions on Software Engineering", "issn": "0098-5589", "jcr_if": 7.6, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE Transactions on Computers", "issn": "0018-9340", "jcr_if": 3.5, "jcr_quartile": "Q2", "cas_quartile": "3区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE Transactions on Parallel and Distributed Systems", "issn": "1045-9219", "jcr_if": 5.6, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE Transactions on Visualization and Computer Graphics", "issn": "1077-2626", "jcr_if": 5.2, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE Transactions on Robotics", "issn": "1552-3098", "jcr_if": 9.4, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE Transactions on Automation Science and Engineering", "issn": "1545-5955", "jcr_if": 5.6, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE Transactions on Industrial Informatics", "issn": "1551-3203", "jcr_if": 11.7, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE Transactions on Dependable and Secure Computing", "issn": "1545-5971", "jcr_if": 7.3, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE Transactions on Information Forensics and Security", "issn": "1556-6013", "jcr_if": 7.2, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE Transactions on Wireless Communications", "issn": "1536-1276", "jcr_if": 5.4, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE Transactions on Communications", "issn": "0090-6778", "jcr_if": 6.2, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE Transactions on Signal Processing", "issn": "1053-587X", "jcr_if": 5.4, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "IEEE/ACM Transactions on Networking", "issn": "1063-6692", "jcr_if": 4.2, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "ACM Transactions on Graphics", "issn": "0730-0301", "jcr_if": 7.4, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "ACM Transactions on Software Engineering and Methodology", "issn": "1049-331X", "jcr_if": 3.8, "jcr_quartile": "Q2", "cas_quartile": "3区", "cas_top": False, "ei_indexed": True},
        {"title": "ACM Transactions on Database Systems", "issn": "0362-5915", "jcr_if": 2.8, "jcr_quartile": "Q2", "cas_quartile": "3区", "cas_top": False, "ei_indexed": True},
        {"title": "ACM Computing Surveys", "issn": "0360-0300", "jcr_if": 16.6, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Artificial Intelligence", "issn": "0004-3702", "jcr_if": 14.05, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "Journal of Machine Learning Research", "issn": "1532-4435", "jcr_if": 6.0, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Neural Networks", "issn": "0893-6080", "jcr_if": 7.8, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Pattern Recognition", "issn": "0031-3203", "jcr_if": 8.518, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "Computer Vision and Image Understanding", "issn": "1077-3142", "jcr_if": 5.0, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Image and Vision Computing", "issn": "0262-8856", "jcr_if": 4.7, "jcr_quartile": "Q2", "cas_quartile": "3区", "cas_top": False, "ei_indexed": True},
        {"title": "Machine Learning", "issn": "0885-6125", "jcr_if": 4.0, "jcr_quartile": "Q2", "cas_quartile": "3区", "cas_top": False, "ei_indexed": True},
        {"title": "Data Mining and Knowledge Discovery", "issn": "1384-5810", "jcr_if": 3.6, "jcr_quartile": "Q2", "cas_quartile": "3区", "cas_top": False, "ei_indexed": True},
        {"title": "Information Sciences", "issn": "0020-0255", "jcr_if": 8.1, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Knowledge-Based Systems", "issn": "0950-7051", "jcr_if": 8.8, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Neurocomputing", "issn": "0925-2312", "jcr_if": 5.5, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Expert Systems with Applications", "issn": "0957-4174", "jcr_if": 8.5, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Applied Soft Computing", "issn": "1568-4946", "jcr_if": 8.7, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Future Generation Computer Systems", "issn": "0167-739X", "jcr_if": 7.5, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Journal of Systems and Software", "issn": "0164-1212", "jcr_if": 3.5, "jcr_quartile": "Q2", "cas_quartile": "3区", "cas_top": False, "ei_indexed": True},
    ],
    "Physics": [
        {"title": "Physical Review Letters", "issn": "0031-9007", "jcr_if": 9.185, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": True},
        {"title": "Physical Review B", "issn": "2469-9950", "jcr_if": 3.7, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Physical Review D", "issn": "2470-0010", "jcr_if": 4.8, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Physical Review E", "issn": "2470-0045", "jcr_if": 2.5, "jcr_quartile": "Q2", "cas_quartile": "3区", "cas_top": False, "ei_indexed": True},
        {"title": "Physical Review A", "issn": "2469-9926", "jcr_if": 3.2, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Physical Review C", "issn": "2469-9985", "jcr_if": 3.1, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Reviews of Modern Physics", "issn": "0034-6861", "jcr_if": 54.3, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": True},
        {"title": "Journal of Fluid Mechanics", "issn": "0022-1120", "jcr_if": 3.8, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Physics of Fluids", "issn": "1070-6631", "jcr_if": 4.6, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Journal of Computational Physics", "issn": "0021-9991", "jcr_if": 4.1, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "European Physical Journal C", "issn": "1434-6044", "jcr_if": 4.9, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "European Physical Journal B", "issn": "1434-6028", "jcr_if": 2.1, "jcr_quartile": "Q2", "cas_quartile": "3区", "cas_top": False, "ei_indexed": True},
        {"title": "Journal of Physics G: Nuclear and Particle Physics", "issn": "0954-3899", "jcr_if": 4.1, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Journal of Physics: Condensed Matter", "issn": "0953-8984", "jcr_if": 2.7, "jcr_quartile": "Q2", "cas_quartile": "3区", "cas_top": False, "ei_indexed": True},
        {"title": "Nuclear Physics B", "issn": "0550-3213", "jcr_if": 4.5, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Nuclear Instruments and Methods in Physics Research A", "issn": "0168-9002", "jcr_if": 1.8, "jcr_quartile": "Q2", "cas_quartile": "3区", "cas_top": False, "ei_indexed": True},
        {"title": "Physics Letters B", "issn": "0370-2693", "jcr_if": 4.8, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Applied Physics Letters", "issn": "0003-6951", "jcr_if": 4.0, "jcr_quartile": "Q2", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Journal of Applied Physics", "issn": "0021-8979", "jcr_if": 3.2, "jcr_quartile": "Q2", "cas_quartile": "3区", "cas_top": False, "ei_indexed": True},
        {"title": "Review of Scientific Instruments", "issn": "0034-6748", "jcr_if": 1.8, "jcr_quartile": "Q2", "cas_quartile": "3区", "cas_top": False, "ei_indexed": True},
    ],
    "Chemistry": [
        {"title": "Journal of the American Chemical Society", "issn": "0002-7863", "jcr_if": 16.383, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": True},
        {"title": "Angewandte Chemie International Edition", "issn": "1433-7851", "jcr_if": 16.823, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": True},
        {"title": "Chemical Reviews", "issn": "0009-2665", "jcr_if": 62.1, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": True},
        {"title": "Chemical Society Reviews", "issn": "0306-0012", "jcr_if": 46.2, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": True},
        {"title": "Accounts of Chemical Research", "issn": "0001-4842", "jcr_if": 24.3, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": True},
        {"title": "Nature Chemistry", "issn": "1755-4330", "jcr_if": 23.5, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
        {"title": "ACS Catalysis", "issn": "2155-5435", "jcr_if": 13.7, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "ACS Nano", "issn": "1936-0851", "jcr_if": 17.1, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": True},
        {"title": "Journal of Organic Chemistry", "issn": "0022-3263", "jcr_if": 3.5, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Journal of Physical Chemistry A", "issn": "1089-5639", "jcr_if": 2.9, "jcr_quartile": "Q2", "cas_quartile": "3区", "cas_top": False, "ei_indexed": True},
        {"title": "Journal of Physical Chemistry B", "issn": "1520-6106", "jcr_if": 3.2, "jcr_quartile": "Q2", "cas_quartile": "3区", "cas_top": False, "ei_indexed": True},
        {"title": "Journal of Physical Chemistry C", "issn": "1932-7447", "jcr_if": 4.1, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Journal of Chemical Physics", "issn": "0021-9606", "jcr_if": 3.1, "jcr_quartile": "Q2", "cas_quartile": "3区", "cas_top": False, "ei_indexed": True},
        {"title": "Physical Chemistry Chemical Physics", "issn": "1463-9076", "jcr_if": 3.7, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Chemical Communications", "issn": "1359-7345", "jcr_if": 6.1, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Dalton Transactions", "issn": "1477-9226", "jcr_if": 4.2, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Organic Letters", "issn": "1523-7060", "jcr_if": 5.2, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Organic Chemistry Frontiers", "issn": "2052-4110", "jcr_if": 5.5, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Green Chemistry", "issn": "1463-9262", "jcr_if": 9.8, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "Catalysis Science & Technology", "issn": "2044-4753", "jcr_if": 5.7, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
    ],
    "Materials Science": [
        {"title": "Advanced Materials", "issn": "0935-9648", "jcr_if": 29.4, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": True},
        {"title": "Nature Materials", "issn": "1476-1122", "jcr_if": 41.2, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": True},
        {"title": "Nano Letters", "issn": "1530-6984", "jcr_if": 12.262, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": True},
        {"title": "ACS Applied Materials & Interfaces", "issn": "1944-8244", "jcr_if": 9.5, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Advanced Functional Materials", "issn": "1616-301X", "jcr_if": 19.0, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": True},
        {"title": "Small", "issn": "1613-6810", "jcr_if": 13.3, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "Nano Today", "issn": "1748-0132", "jcr_if": 18.8, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": True},
        {"title": "Journal of Materials Chemistry A", "issn": "2050-7488", "jcr_if": 12.7, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "Journal of Materials Chemistry B", "issn": "2050-750X", "jcr_if": 7.0, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Journal of Materials Chemistry C", "issn": "2050-7526", "jcr_if": 6.4, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Materials Horizons", "issn": "2051-6347", "jcr_if": 13.3, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "Nanoscale", "issn": "2040-3364", "jcr_if": 6.7, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Nanotechnology", "issn": "0957-4484", "jcr_if": 3.5, "jcr_quartile": "Q2", "cas_quartile": "3区", "cas_top": False, "ei_indexed": True},
        {"title": "Acta Materialia", "issn": "1359-6454", "jcr_if": 9.4, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "Scripta Materialia", "issn": "1359-6462", "jcr_if": 5.2, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Materials Science and Engineering A", "issn": "0921-5093", "jcr_if": 6.4, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Journal of the American Ceramic Society", "issn": "0002-7820", "jcr_if": 4.1, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Ceramics International", "issn": "0272-8842", "jcr_if": 5.5, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Composites Science and Technology", "issn": "0266-3538", "jcr_if": 9.1, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "Carbon", "issn": "0008-6223", "jcr_if": 10.9, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
    ],
    "Medicine": [
        {"title": "The Lancet", "issn": "0140-6736", "jcr_if": 168.9, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
        {"title": "New England Journal of Medicine", "issn": "0028-4793", "jcr_if": 158.5, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
        {"title": "Journal of the American Medical Association", "issn": "0098-7484", "jcr_if": 120.7, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
        {"title": "Nature Medicine", "issn": "1078-8956", "jcr_if": 82.9, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
        {"title": "BMJ", "issn": "0959-8138", "jcr_if": 93.3, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
        {"title": "Annals of Internal Medicine", "issn": "0003-4819", "jcr_if": 43.4, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": False},
        {"title": "PLOS Medicine", "issn": "1549-1277", "jcr_if": 11.0, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": False},
        {"title": "Journal of Clinical Investigation", "issn": "0021-9738", "jcr_if": 19.5, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": False},
        {"title": "Journal of Clinical Oncology", "issn": "0732-183X", "jcr_if": 42.1, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
        {"title": "Cancer Research", "issn": "0008-5472", "jcr_if": 12.5, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": False},
        {"title": "Clinical Cancer Research", "issn": "1078-0432", "jcr_if": 11.5, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": False},
        {"title": "Blood", "issn": "0006-4971", "jcr_if": 25.5, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
        {"title": "Circulation", "issn": "0009-7322", "jcr_if": 37.8, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
        {"title": "Journal of the American College of Cardiology", "issn": "0735-1097", "jcr_if": 24.1, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
        {"title": "European Heart Journal", "issn": "0195-668X", "jcr_if": 35.9, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
        {"title": "Gastroenterology", "issn": "0016-5085", "jcr_if": 29.4, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
        {"title": "Gut", "issn": "0017-5749", "jcr_if": 31.8, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
        {"title": "The Lancet Oncology", "issn": "1470-2045", "jcr_if": 51.1, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
        {"title": "The Lancet Neurology", "issn": "1474-4422", "jcr_if": 46.5, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
        {"title": "The Lancet Infectious Diseases", "issn": "1473-3099", "jcr_if": 56.3, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
    ],
    "Biology": [
        {"title": "Cell", "issn": "0092-8674", "jcr_if": 66.85, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
        {"title": "Nature Cell Biology", "issn": "1465-7392", "jcr_if": 21.3, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": False},
        {"title": "Molecular Cell", "issn": "1097-2765", "jcr_if": 17.9, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": False},
        {"title": "Developmental Cell", "issn": "1534-5807", "jcr_if": 11.8, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": False},
        {"title": "Current Biology", "issn": "0960-9822", "jcr_if": 10.9, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": False},
        {"title": "EMBO Journal", "issn": "0261-4189", "jcr_if": 11.6, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": False},
        {"title": "EMBO Reports", "issn": "1469-221X", "jcr_if": 9.1, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": False},
        {"title": "Proceedings of the National Academy of Sciences", "issn": "0027-8424", "jcr_if": 12.8, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": True, "ei_indexed": True},
        {"title": "eLife", "issn": "2050-084X", "jcr_if": 8.7, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": False},
        {"title": "Genome Biology", "issn": "1465-6906", "jcr_if": 12.3, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": False},
        {"title": "Nucleic Acids Research", "issn": "0305-1048", "jcr_if": 16.6, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "Bioinformatics", "issn": "1367-4803", "jcr_if": 6.9, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "PLoS Biology", "issn": "1544-9173", "jcr_if": 9.6, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": False},
        {"title": "BMC Biology", "issn": "1741-7007", "jcr_if": 6.7, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": False},
        {"title": "Journal of Biological Chemistry", "issn": "0021-9258", "jcr_if": 5.5, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
    ],
    "Engineering": [
        {"title": "Nature Engineering", "issn": "2835-2616", "jcr_if": 12.8, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": False},
        {"title": "Chemical Engineering Journal", "issn": "1385-8947", "jcr_if": 15.1, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "Journal of Power Sources", "issn": "0378-7753", "jcr_if": 9.2, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Applied Energy", "issn": "0306-2619", "jcr_if": 11.2, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "Energy", "issn": "0360-5442", "jcr_if": 9.0, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Energy Conversion and Management", "issn": "0196-8904", "jcr_if": 10.4, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "Desalination", "issn": "0011-9164", "jcr_if": 9.9, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "Journal of Membrane Science", "issn": "0376-7388", "jcr_if": 10.5, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "AIChE Journal", "issn": "0001-1541", "jcr_if": 3.7, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Industrial & Engineering Chemistry Research", "issn": "0888-5885", "jcr_if": 4.2, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Computer Methods in Applied Mechanics and Engineering", "issn": "0045-7825", "jcr_if": 6.9, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "International Journal of Solids and Structures", "issn": "0020-7683", "jcr_if": 3.6, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "International Journal of Heat and Mass Transfer", "issn": "0017-9310", "jcr_if": 5.4, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "International Journal of Plasticity", "issn": "0749-6419", "jcr_if": 7.4, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "Mechanical Systems and Signal Processing", "issn": "0888-3270", "jcr_if": 8.9, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "Renewable Energy", "issn": "0960-1481", "jcr_if": 8.7, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "Solar Energy", "issn": "0038-092X", "jcr_if": 6.0, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Applied Thermal Engineering", "issn": "1359-4311", "jcr_if": 6.9, "jcr_quartile": "Q1", "cas_quartile": "2区", "cas_top": False, "ei_indexed": True},
        {"title": "Journal of Hazardous Materials", "issn": "0304-3894", "jcr_if": 13.6, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
        {"title": "Environmental Science & Technology", "issn": "0013-936X", "jcr_if": 11.4, "jcr_quartile": "Q1", "cas_quartile": "1区", "cas_top": False, "ei_indexed": True},
    ],
}

PUBLISHER_URLS = {
    "Nature Publishing Group": "https://www.nature.com/",
    "Elsevier": "https://www.elsevier.com/",
    "IEEE": "https://www.ieee.org/",
    "ACM": "https://www.acm.org/",
    "Wiley": "https://onlinelibrary.wiley.com/",
    "Wiley-VCH": "https://onlinelibrary.wiley.com/",
    "American Chemical Society": "https://pubs.acs.org/",
    "American Physical Society": "https://journals.aps.org/",
    "Cell Press": "https://www.cell.com/",
    "Springer Nature": "https://www.springernature.com/",
    "Taylor & Francis": "https://www.tandfonline.com/",
    "Oxford University Press": "https://academic.oup.com/",
    "Cambridge University Press": "https://www.cambridge.org/",
    "Royal Society of Chemistry": "https://pubs.rsc.org/",
    "AIP Publishing": "https://aip.scitation.org/",
    "IOP Publishing": "https://iopscience.iop.org/",
    "American Association for the Advancement of Science": "https://www.science.org/",
    "Massachusetts Medical Society": "https://www.nejm.org/",
    "BMJ Publishing Group": "https://www.bmj.com/",
    "American Medical Association": "https://jamanetwork.com/",
}

CATEGORIES_JCR = [
    "Computer Science, Artificial Intelligence",
    "Computer Science, Theory & Methods",
    "Computer Science, Software Engineering",
    "Computer Science, Information Systems",
    "Computer Science, Cybernetics",
    "Physics, Multidisciplinary",
    "Physics, Applied",
    "Physics, Condensed Matter",
    "Physics, Atomic, Molecular & Chemical",
    "Physics, Mathematical",
    "Chemistry, Multidisciplinary",
    "Chemistry, Physical",
    "Chemistry, Organic",
    "Chemistry, Analytical",
    "Materials Science, Multidisciplinary",
    "Materials Science, Ceramics",
    "Nanoscience & Nanotechnology",
    "Medicine, General & Internal",
    "Medicine, Research & Experimental",
    "Biochemistry & Molecular Biology",
    "Cell Biology",
    "Genetics & Heredity",
    "Immunology",
    "Neurosciences",
    "Engineering, Chemical",
    "Engineering, Biomedical",
    "Energy & Fuels",
    "Mechanics",
    "Multidisciplinary Sciences",
]